{{- range .Values.additional_ingresses -}}
{{- $fullName := include "helm.fullname" $ -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
  annotations:
  {{- toYaml .annotations | nindent 4}}
spec:
  ingressClassName: {{ .className }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if not .host }}
    - http:
  {{- else}}
    - host: {{ .host }}
      http:
  {{- end}}

        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
---
{{- end }}
