{{- if .Values.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.additionalServicePorts }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    {{- if .Values.additionalPods }}
    app: "{{ .Chart.Name }}"
    {{- end }}
{{- end }}
